name: Bug Report
description: Report a bug or issue with the Alnor integration
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have read the [documentation](https://github.com/nashant/ha-alnor/blob/main/README.md)
          required: true
        - label: I have checked [existing issues](https://github.com/nashant/ha-alnor/issues) for duplicates
          required: true
        - label: I have enabled debug logging and included relevant logs
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: "2024.1.0"
    validations:
      required: true

  - type: input
    id: integration-version
    attributes:
      label: Integration Version
      description: What version of the Alnor integration are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: Which device is affected?
      options:
        - HRU-PremAir-450
        - HRU-PremAir-500
        - VMC-02VJ04 (Exhaust Fan)
        - VMS-02C05 (CO2 Sensor)
        - VMI-02MC02 (Humidity Sensor)
        - Other (please specify below)
        - Multiple devices
        - Not device-specific
    validations:
      required: true

  - type: dropdown
    id: connection-mode
    attributes:
      label: Connection Mode
      description: Are you using cloud or local Modbus TCP?
      options:
        - Cloud API only
        - Local Modbus TCP
        - Both (mixed)
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please include relevant logs with debug logging enabled.
        To enable debug logging, add to configuration.yaml:
        ```yaml
        logger:
          default: info
          logs:
            custom_components.alnor: debug
            alnor_sdk: debug
        ```
        **Important:** Remove any sensitive information (passwords, tokens, etc.)
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        If relevant, share your configuration (YAML snippets, automation rules, etc.)
        **Important:** Remove sensitive information
      render: yaml
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, error messages, etc.)
    validations:
      required: false
