name: Feature Request
description: Suggest an idea or enhancement for the Alnor integration
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have read the [documentation](https://github.com/nashant/ha-alnor/blob/main/README.md)
          required: true
        - label: I have checked [existing issues](https://github.com/nashant/ha-alnor/issues) for similar requests
          required: true
        - label: This feature is related to the Alnor integration (not Home Assistant core)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - New device support
        - New sensor/entity type
        - Configuration/setup improvement
        - Automation/integration enhancement
        - Performance improvement
        - Documentation
        - User interface
        - Other
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type (if applicable)
      description: Which device type is this related to?
      options:
        - Heat Recovery Unit (HRU)
        - Exhaust Fan
        - Environmental Sensor
        - Bridge/Gateway
        - All devices
        - Not device-specific
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature? Provide specific examples.
      placeholder: |
        Example scenario:
        1. I want to...
        2. So that I can...
        3. This would help with...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Willing to Contribute
      description: Are you willing to help implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, I can help test"
        - "Yes, I can provide feedback"
        - "No, but I can provide more details"
        - "Not at this time"
    validations:
      required: false
